### ISSUE TITLE
有编译好的吗

### ISSUE THREAD

**Issue by linux-hub** [orcastor/cad2x-converter#1]

**Comment by orca-zhang** [comment]
linux arm64和linux x64版本挂在主页了

<p>Pre-built <strong>cad2x</strong>: <a href="https://github.com/orcastor/addon-previewer/tree/main/back/cad2x/linux_arm64"><strong>linux_arm64</strong></a> (2.88MB) | <a href="https://github.com/orcastor/addon-previewer/tree/main/back/cad2x/linux_x64"><strong>linux_x64</strong></a> (3.42MB)
</p>

**Comment by 8502596** [comment]
他应该说的是 Windows 环境下   废了九牛二虎之力  编译的  应该需要安装 QT 5.12.12  及配置path  bin目录
[cad2x.zip](https://github.com/orcastor/cad2x-converter/files/14414927/cad2x.zip)

**Comment by orca-zhang** [comment]
感谢提供windows版本
