### ISSUE TITLE
乱码 dwg  to  dxf 

### ISSUE THREAD

**Issue by 8502596** [orcastor/cad2x-converter#2]
DWG  to  dxf  有ASNI-936  选项吗？ 添加了  cad2x.exe -o a-43.dxf -e ASNI-936 a-43.dwg   不起作用 ，
小白  无论加不加   -e ASNI-936  都会是

![1](https://github.com/orcastor/cad2x-converter/assets/15864647/bdfe8b3e-1ef4-4bdb-94b4-2dd28866d7d6)

**Comment by 8502596** [comment]
[a-43.zip](https://github.com/orcastor/cad2x-converter/files/14401033/a-43.zip)
测试文件

**Comment by orca-zhang** [comment]
是下划线，不是中划线

**Comment by 8502596** [comment]
改成ANSI_936 还是不行  依旧是乱码  依旧是AutoCAD 打不开  但WPS 里面的浩辰CAD 能打开，
![image](https://github.com/orcastor/cad2x-converter/assets/15864647/ccc4a423-2f65-4dfa-90ff-74a8c86ebcaf)

这个测试 [https://github.com/orcastor/cad2x-converter/files/14401033/a-43.zip](url)  用AutoCAD 是能转换成中文编码的 UTF-8 格式的 dxf 文件的  dwg文件1014    2007之前都是GB2312  ANSI_936之类的，感觉他少一步呢，调试程序把我绕晕了，用GBK等读取dwg 用UTF-8写入文件 应该是这个套路

**Comment by 8502596** [comment]
还有个问题  vs调试 debug  和 命令行执行 结果文件大小不一致  相差极大 也不知道啥情况  

https://www.jianshu.com/p/3594f65f6a53  dwg格式编码  程序装载dwg 读取文件似乎并没有考虑编码的问题

**Comment by 8502596** [comment]
还有个问题  vs调试 debug  和 命令行执行 结果文件大小不一致  相差极大 也不知道啥情况  

https://www.jianshu.com/p/3594f65f6a53  dwg格式编码  程序装载dwg 读取文件似乎并没有考虑编码的问题

**Comment by orca-zhang** [comment]
可以本地先安装LibreCAD 和QCad分别实际测试一下原版能不能支持编码
