### ISSUE TITLE
ubuntu 22.04 编译失败

### ISSUE THREAD

**Issue by YangDaiJun** [orcastor/cad2x-converter#3]
In file included from ../3rdparty/qtbase/include/QtCore/qtextstream.h:1,
                 from ../3rdparty/qtbase/include/QtCore/QTextStream:1,
                 from rs_debug.h:32,
                 from rs_arc.cpp:38:
../3rdparty/qtbase/include/QtCore/../../src/corelib/serialization/qtextstream.h:230:21: note: candidate: ‘QTextStream& operator<<(QTextStream&, QTextStreamFunction)’
  230 | inline QTextStream &operator<<(QTextStream &s, QTextStreamFunction f)
      |                     ^~~~~~~~
../3rdparty/qtbase/include/QtCore/../../src/corelib/serialization/qtextstream.h:230:45: note:   no known conversion for argument 1 from ‘std::ostream’ {aka ‘std::basic_ostream<char>’} to ‘QTextStream&’
  230 | inline QTextStream &operator<<(QTextStream &s, QTextStreamFunction f)
      |                                ~~~~~~~~~~~~~^
../3rdparty/qtbase/include/QtCore/../../src/corelib/serialization/qtextstream.h:233:21: note: candidate: ‘QTextStream& operator<<(QTextStream&, QTextStreamManipulator)’
  233 | inline QTextStream &operator<<(QTextStream &s, QTextStreamManipulator m)
      |                     ^~~~~~~~
../3rdparty/qtbase/include/QtCore/../../src/corelib/serialization/qtextstream.h:233:45: note:   no known conversion for argument 1 from ‘std::ostream’ {aka ‘std::basic_ostream<char>’} to ‘QTextStream&’
  233 | inline QTextStream &operator<<(QTextStream &s, QTextStreamManipulator m)
      |                                ~~~~~~~~~~~~~^
rs_arc.cpp:1057:15: note: candidate: ‘std::ostream& operator<<(std::ostream&, const RS_Arc&)’
 1057 | std::ostream& operator << (std::ostream& os, const RS_Arc& a) {
      |               ^~~~~~~~
rs_arc.cpp:1057:60: note:   no known conversion for argument 2 from ‘const char [7]’ to ‘const RS_Arc&’
 1057 | std::ostream& operator << (std::ostream& os, const RS_Arc& a) {
      |                                              ~~~~~~~~~~~~~~^
make[1]: *** [Makefile:2187: ../generated/cad2x/obj/rs_arc.o] Error 1
make[1]: Leaving directory '/home/yangdj/cad2x-converter-master/src'
make: *** [Makefile:91: sub-src-make_first-ordered] Error 2

**Comment by orca-zhang** [comment]
人在外地，等我回去看下

**Comment by YangDaiJun** [comment]
谢谢，我下载了编译好的程序，但是转换后文字消息了。
环境是WSL windows10 具体版本：Linux DESKTOP-ABO5V41 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by orca-zhang** [comment]
我这边没有能够复现，不过我把所有stdout的输出相关无用代码删除掉了，再编译看看，然后最后一句说的`转换后文字消息`是什么意思呢？是显示什么错误信息了吗？
