### ISSUE TITLE
ubuntu 18.04编译失败

### ISSUE THREAD

**Issue by Zxg2001** [orcastor/cad2x-converter#5]
root@ubuntu:/opt/cad2x-converter/3rdparty/qtbase# ./configure 
Creating qmake...
cat: /opt/cad2x-converter/3rdparty/qtbase/qmake/Makefile.unix.unix: No such file or directory
cat: /opt/cad2x-converter/3rdparty/qtbase/qmake/Makefile.unix: No such file or directory
make: *** No targets.  Stop.

**Comment by orca-zhang** [comment]
I've uploaded left behind files in commit 4d418fb.
